per_page: 5
gravatar_size: 50
micropost:
  content_length: 4890
  picture_size: 5
  title_length: 150
user:
  user_per_page: 10
  gravatar_size: 30
  name_size: 50
  email_size: 255
  password_minium: 1
